{
  "name": "main",
  "on": {
    "push": {
      "branches": ["main"],
      "tags": ["*"]
    },
    "pull_request": {
      "branches": [
        "main"
      ]
    }
  },
  "jobs": {
    "test": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "name": "setup | checkout",
          "uses": "actions/checkout@v2"
        },
        {
          "name": "setup | deno",
          "uses": "denolib/setup-deno@v2",
          "with": {
            "deno-version": "1.20.6"
          }
        },
        {
          "name": "test | run module",
          "run": "deno run --reload mod.ts"
        },
        {
          "name": "test | test",
          "run": "deno test --allow-none"
        }
      ]
    }
  }
}
